# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: Docker@2
  inputs:
    containerRegistry: 'octolabRegistry'
    repository: 'hello-app'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

- task: OctopusPack@4
  inputs:
    PackageId: 'HelloApp'
    PackageFormat: 'Zip'
    PackageVersion: '$(Build.BuildNumber)'
    SourcePath: 'k8s'
    OutputPath: '$(Build.ArtifactStagingDirectory)'
    Include: '$(Build.SourcesDirectory)/k8s'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'OctupusPkg'
    publishLocation: 'Container'
  
- task: OctopusPush@4
  inputs:
    OctoConnectedServiceName: 'srcilabvm01'
    Package: 'HelloApp'
    Space: 'Default'
    Replace: 'false'